#!/bin/bash

ALX School is so coo                                                                                                                                            

=======                                                                                                                                                             

ALX School                                                                                                                                                          

